# Generated by Django 3.1.1 on 2021-04-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('año', models.IntegerField()),
                ('editorial', models.CharField(blank=True, max_length=100)),
                ('edicion', models.CharField(blank=True, max_length=100)),
                ('resumen', models.TextField(default='Resumen...', max_length=500)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
