# Generated by Django 3.1.1 on 2021-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tema',
            field=models.CharField(choices=[('literatura', 'Lilteratura'), ('matematica', 'Matematica'), ('comunicacion', 'Comunicación y Lenguaje'), ('historia', 'Historia'), ('varios', 'Libros varios')], default='Tema libro', max_length=50),
        ),
    ]
