# Generated by Django 3.1.1 on 2021-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20210416_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tema',
            field=models.CharField(choices=[('Literatura', 'Literatura'), ('Matemática', 'Matemática'), ('Comunicación', 'Comunicación y Lenguaje'), ('Historia', 'Historia'), ('Varios', 'Libros varios')], max_length=50),
        ),
    ]
