# Generated by Django 3.1.1 on 2021-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_auto_20210416_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='link',
            field=models.URLField(),
        ),
    ]
